{
 "title": "Homework Dashboard",
 "time": { "from": "2024-03-01T00:00:00.000Z", "to": "2024-03-31T00:00:00.000Z" },
 "panels": [
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM dummy_metrics_hw LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics_hw LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare amount quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fare_amount_quantile FROM dummy_metrics_hw LIMIT 50 "
    }
   ]
  }
 ]
}